### ISSUE TITLE
Test case fails when build env has java version with no minor.

### ISSUE THREAD

**Issue by dhingra** [yggdrash/yggdrash#1]
Test case fails for below env , as it doesn't have minor.

java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode

![screen shot 2018-06-10 at 1 27 52 am](https://user-images.githubusercontent.com/7157372/41198545-a9a6e5a8-6c4d-11e8-8e49-d9aa9f815801.png)

**Comment by popldo** [comment]
That code is comming ethereumj, you are not compile ethereumj?

**Comment by ghost** [comment]
You'd like to check your application or shell about JAVA_HOME setting.

**Comment by dhingra** [comment]
Hello Gents,
method  getJavaVersion() in io.yggdrash.util.Utils.java assumes java version to be in format major.minor_build. So test9 in CyrptoTest.java doesn't fail when java version is 1.8.0_144
but it fails when java version is "9".

It's not a show stopper, but user has to change env to so that version has minor.

Fix is done to address this. 

Thanks,

**Comment by dhingra** [comment]
and the reason I have not used ./gradlew because "yggdrash/gradle/wrapper/"  is missing gradle-wrapper.jar.

**Comment by popldo** [comment]
pr #2 issue closed
