### ISSUE TITLE
[TestNet-Node] init: required argument missing

### ISSUE THREAD

**Issue by DuckingElias** [yggdrash/yggdrash#302]
The Developer Guide (https://developers.yggdrash.io/en/guide/test-net.html#wallet-guide) says, that you only need to type in 
 `./yggdrash init`
But when i do that, it says that it is missing an argument:
![image](https://user-images.githubusercontent.com/46087722/63555559-b0b97100-c541-11e9-8d1e-9c7503039f23.png)

**Comment by ghost** [comment]
Dear @RagingElias 

First of all, thank you for your interest.
We updated the [guide](https://developers.yggdrash.io/en/guide/test-net.html#node-sync-guide) at this time.


Have a nice day!
by Jaes.
